name: Run Test
on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: | 
          cat ./sample.txt